// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBV.Models;

#nullable disable

namespace QLBV.Migrations
{
    [DbContext(typeof(QLBVContext))]
    partial class QLBVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QLBV.Models.ArchiveNhanVien", b =>
                {
                    b.Property<int>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArchiveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchiveId"));

                    b.Property<DateTime?>("ArchivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenNv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenNV");

                    b.Property<string>("LoaiNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPB");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("ArchiveId")
                        .HasName("PK__Archive___33A73E7754E8CA88");

                    b.ToTable("Archive_NhanVien");
                });

            modelBuilder.Entity("QLBV.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RecordID");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Audit_Lo__3214EC27BF5897A4");

                    b.ToTable("Audit_Log");
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.Property<string>("MaBs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBS");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBs")
                        .HasName("PK__BacSi__27247596C0E20624");

                    b.ToTable("BacSi");

                    b.HasData(
                        new
                        {
                            MaBs = "BS001",
                            TrinhDo = "Tiến sĩ Y khoa"
                        },
                        new
                        {
                            MaBs = "BS002",
                            TrinhDo = "Phó Giáo sư, Tiến sĩ"
                        },
                        new
                        {
                            MaBs = "BS003",
                            TrinhDo = "Bác sĩ Chuyên khoa II"
                        });
                });

            modelBuilder.Entity("QLBV.Models.BacSiArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaBs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBS");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("BacSi_Archive");
                });

            modelBuilder.Entity("QLBV.Models.BenhNhan", b =>
                {
                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBN");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenBn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenBN");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaBn")
                        .HasName("PK__BenhNhan__272475ADE7DE9241");

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("QLBV.Models.BenhNhanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenBn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenBN");

                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBN");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.ToTable("BenhNhan_Archive");
                });

            modelBuilder.Entity("QLBV.Models.BoPhan", b =>
                {
                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBP");

                    b.Property<string>("TenBoPhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBp")
                        .HasName("PK__BoPhan__272475ABE52F0BF5");

                    b.ToTable("BoPhan");

                    b.HasData(
                        new
                        {
                            MaBp = "BPQL",
                            TenBoPhan = "Bộ phận quản lý"
                        },
                        new
                        {
                            MaBp = "BPTTDP",
                            TenBoPhan = "Bộ phận tiếp tân và điều phối"
                        },
                        new
                        {
                            MaBp = "BPDT",
                            TenBoPhan = "Bộ phận điều trị"
                        },
                        new
                        {
                            MaBp = "BPTV",
                            TenBoPhan = "Bộ phận tài vụ"
                        },
                        new
                        {
                            MaBp = "BPKT",
                            TenBoPhan = "Bộ phận kế toán"
                        },
                        new
                        {
                            MaBp = "BPDNT",
                            TenBoPhan = "Bộ phận dược – nhà thuốc"
                        });
                });

            modelBuilder.Entity("QLBV.Models.BoPhanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBP");

                    b.Property<string>("TenBoPhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("BoPhan_Archive");
                });

            modelBuilder.Entity("QLBV.Models.CaTruc", b =>
                {
                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCT");

                    b.Property<string>("Nvtruc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NVtruc");

                    b.Property<DateTime?>("ThoiGianBt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianBT");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianKT");

                    b.HasKey("MaCt")
                        .HasName("PK__CaTruc__27258E740132F318");

                    b.HasIndex("Nvtruc");

                    b.ToTable("CaTruc");
                });

            modelBuilder.Entity("QLBV.Models.CaTrucArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCT");

                    b.Property<string>("Nvtruc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NVtruc");

                    b.Property<DateTime?>("ThoiGianBt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianBT");

                    b.Property<DateTime?>("ThoiGianKt")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianKT");

                    b.ToTable("CaTruc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKham", b =>
                {
                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPK");

                    b.Property<string>("MaTt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaTT");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TtthanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TTThanhToan");

                    b.HasKey("MaPk", "MaTt");

                    b.HasIndex("MaTt");

                    b.ToTable("ChiTietPhieuKham");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKhamArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPK");

                    b.Property<string>("MaTt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaTT");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TtthanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TTThanhToan");

                    b.ToTable("ChiTietPhieuKham_Archive");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhap", "MaThuoc")
                        .HasName("PK__ChiTietP__00CBF05937EC544E");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhapArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.ToTable("ChiTietPhieuNhap_Archive");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuoc", b =>
                {
                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaToaThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietToaThuoc");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("ChiTietToaThuoc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgayApDung")
                        .HasColumnType("date");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MaThuoc", "NgayApDung")
                        .HasName("PK__GiaBanTh__1E11655E12D3EF1E");

                    b.ToTable("GiaBanThuoc");

                    b.HasData(
                        new
                        {
                            MaThuoc = "TH001",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 15000m
                        },
                        new
                        {
                            MaThuoc = "TH002",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 35000m
                        },
                        new
                        {
                            MaThuoc = "TH003",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 20000m
                        },
                        new
                        {
                            MaThuoc = "TH004",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 18000m
                        },
                        new
                        {
                            MaThuoc = "TH005",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 22000m
                        },
                        new
                        {
                            MaThuoc = "TH006",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 28000m
                        },
                        new
                        {
                            MaThuoc = "TH007",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 16000m
                        },
                        new
                        {
                            MaThuoc = "TH008",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 40000m
                        },
                        new
                        {
                            MaThuoc = "TH009",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 25000m
                        },
                        new
                        {
                            MaThuoc = "TH010",
                            NgayApDung = new DateOnly(2025, 5, 1),
                            GiaBan = 19000m
                        });
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayApDung")
                        .HasColumnType("date");

                    b.ToTable("GiaBanThuoc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.Luong", b =>
                {
                    b.Property<string>("MaLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("LuongCoBan")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("NgayCong")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(20, 2)");

                    b.HasKey("MaLuong")
                        .HasName("PK__Luong__6609A48D447B4DD4");

                    b.HasIndex("MaNv");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("QLBV.Models.LuongArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("LuongCoBan")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<string>("MaLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("NgayCong")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(20, 2)");

                    b.ToTable("Luong_Archive");
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenNv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenNV");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPB");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A3933CAA9");

                    b.HasIndex("MaPb");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNv = "BS001",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Hoàng Phong",
                            MaPb = "PBKN",
                            NgaySinh = new DateOnly(1980, 11, 15),
                            Sdt = "0987123456"
                        },
                        new
                        {
                            MaNv = "BS002",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Quang Ngọc",
                            MaPb = "PBKG",
                            NgaySinh = new DateOnly(1975, 8, 22),
                            Sdt = "0912345678"
                        },
                        new
                        {
                            MaNv = "BS003",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Trần Gia Huy",
                            MaPb = "PBKNHI",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV001",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Lê Nguyễn Minh Hoàng",
                            MaPb = "PBQLNS",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV002",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Phan Võ Anh Hào",
                            MaPb = "PBQLTV",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV003",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Quách Tuấn Anh",
                            MaPb = "PBQLCM",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV004",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Văn A",
                            MaPb = "PBTTDP",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV005",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Nguyễn Văn B",
                            MaPb = "PBTTV",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV006",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Trần Thị C",
                            MaPb = "PBKT",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        },
                        new
                        {
                            MaNv = "NV007",
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            HoTenNv = "Lê Văn D",
                            MaPb = "PBBT",
                            NgaySinh = new DateOnly(1982, 3, 30),
                            Sdt = "0978123456"
                        });
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPK");

                    b.Property<string>("Bacsi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaSoKham")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayKham")
                        .HasColumnType("date");

                    b.Property<string>("NguoiKham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPk")
                        .HasName("PK__PhieuKha__2725E7FD2B331110");

                    b.HasIndex("Bacsi");

                    b.HasIndex("MaSoKham");

                    b.HasIndex("NguoiKham");

                    b.ToTable("PhieuKhamBenh");
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenhArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Bacsi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPK");

                    b.Property<DateOnly?>("NgayKham")
                        .HasColumnType("date");

                    b.Property<string>("NguoiKham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("PhieuKhamBenh_Archive");
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuoc", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B4153D383");

                    b.ToTable("PhieuNhapThuoc", null, t =>
                        {
                            t.HasTrigger("trg_Audit_PhieuNhapThuoc");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("PhieuNhapThuoc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPB");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBP");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPb")
                        .HasName("PK__PhongBan__2725E7E43C0AFEA3");

                    b.HasIndex("MaBp");

                    b.ToTable("PhongBan");

                    b.HasData(
                        new
                        {
                            MaPb = "PBQLNS",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý tài nguyên nhân sự"
                        },
                        new
                        {
                            MaPb = "PBQLTV",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý tài vụ"
                        },
                        new
                        {
                            MaPb = "PBQLCM",
                            MaBp = "BPQL",
                            TenPhongBan = "Phòng quản lý chuyên môn"
                        },
                        new
                        {
                            MaPb = "PBTTDP",
                            MaBp = "BPTTDP",
                            TenPhongBan = "Phòng tiếp tân và điều phối"
                        },
                        new
                        {
                            MaPb = "PBKN",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa nội"
                        },
                        new
                        {
                            MaPb = "PBKG",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa ngoại"
                        },
                        new
                        {
                            MaPb = "PBKNHI",
                            MaBp = "BPDT",
                            TenPhongBan = "Phòng khoa nhi"
                        },
                        new
                        {
                            MaPb = "PBTTV",
                            MaBp = "BPTV",
                            TenPhongBan = "Phòng tài vụ"
                        },
                        new
                        {
                            MaPb = "PBKT",
                            MaBp = "BPKT",
                            TenPhongBan = "Phòng kế toán"
                        },
                        new
                        {
                            MaPb = "PBBT",
                            MaBp = "BPDNT",
                            TenPhongBan = "Phòng bán thuốc"
                        });
                });

            modelBuilder.Entity("QLBV.Models.PhongBanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaBp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBP");

                    b.Property<string>("MaPb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPB");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("PhongBan_Archive");
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.Property<int>("MaSoKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoKham"));

                    b.Property<string>("MaBn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaBN");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaPK");

                    b.HasKey("MaSoKham");

                    b.HasIndex("MaBn");

                    b.ToTable("SoKhamBenh");
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaTK");

                    b.Property<string>("LoaiTk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiTK");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<byte[]>("Mk")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)")
                        .HasColumnName("MK");

                    b.Property<string>("TenDn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDN");

                    b.HasKey("MaTk")
                        .HasName("PK__TaiKhoan__272500700D0EAAA4");

                    b.HasIndex(new[] { "MaNv" }, "UQ__TaiKhoan__2725D70B0150A028")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("TaiKhoan", null, t =>
                        {
                            t.HasTrigger("trg_Audit_TaiKhoan_InsertUpdate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoanArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LoaiTk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiTK");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaTk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaTK");

                    b.Property<byte[]>("Mk")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)")
                        .HasColumnName("MK");

                    b.Property<string>("TenDn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDN");

                    b.ToTable("TaiKhoan_Archive");
                });

            modelBuilder.Entity("QLBV.Models.ThuTuc", b =>
                {
                    b.Property<string>("MaThuTuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenTuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThuTuc")
                        .HasName("PK__ThuTuc__3A19BB26367D849A");

                    b.ToTable("ThuTuc");

                    b.HasData(
                        new
                        {
                            MaThuTuc = "TT001",
                            DonGia = 150000.00m,
                            TenTuc = "Khám tổng quát"
                        },
                        new
                        {
                            MaThuTuc = "TT002",
                            DonGia = 80000.00m,
                            TenTuc = "Xét nghiệm máu"
                        },
                        new
                        {
                            MaThuTuc = "TT003",
                            DonGia = 120000.00m,
                            TenTuc = "Chụp X-quang phổi"
                        },
                        new
                        {
                            MaThuTuc = "TT004",
                            DonGia = 200000.00m,
                            TenTuc = "Siêu âm bụng tổng quát"
                        },
                        new
                        {
                            MaThuTuc = "TT005",
                            DonGia = 100000.00m,
                            TenTuc = "Đo điện tim (ECG)"
                        },
                        new
                        {
                            MaThuTuc = "TT006",
                            DonGia = 90000.00m,
                            TenTuc = "Khám tai mũi họng"
                        },
                        new
                        {
                            MaThuTuc = "TT007",
                            DonGia = 350000.00m,
                            TenTuc = "Nội soi dạ dày"
                        },
                        new
                        {
                            MaThuTuc = "TT008",
                            DonGia = 50000.00m,
                            TenTuc = "Xét nghiệm nước tiểu"
                        },
                        new
                        {
                            MaThuTuc = "TT009",
                            DonGia = 70000.00m,
                            TenTuc = "Tiêm ngừa cúm"
                        },
                        new
                        {
                            MaThuTuc = "TT010",
                            DonGia = 250000.00m,
                            TenTuc = "Khám chuyên khoa tim mạch"
                        });
                });

            modelBuilder.Entity("QLBV.Models.ThuTucArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaThuTuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("ThuTuc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.Thuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThuoc")
                        .HasName("PK__Thuoc__4BB1F62060EBE1A0");

                    b.ToTable("Thuoc");

                    b.HasData(
                        new
                        {
                            MaThuoc = "TH001",
                            DonVi = "Vỉ",
                            TenThuoc = "Paracetamol 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH002",
                            DonVi = "Vỉ",
                            TenThuoc = "Amoxicillin 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH003",
                            DonVi = "Vỉ",
                            TenThuoc = "Vitamin C 500mg"
                        },
                        new
                        {
                            MaThuoc = "TH004",
                            DonVi = "Vỉ",
                            TenThuoc = "Ibuprofen 200mg"
                        },
                        new
                        {
                            MaThuoc = "TH005",
                            DonVi = "Vỉ",
                            TenThuoc = "Loratadine 10mg"
                        },
                        new
                        {
                            MaThuoc = "TH006",
                            DonVi = "Vỉ",
                            TenThuoc = "Omeprazole 20mg"
                        },
                        new
                        {
                            MaThuoc = "TH007",
                            DonVi = "Vỉ",
                            TenThuoc = "Salbutamol 2mg"
                        },
                        new
                        {
                            MaThuoc = "TH008",
                            DonVi = "Vỉ",
                            TenThuoc = "Cefixime 200mg"
                        },
                        new
                        {
                            MaThuoc = "TH009",
                            DonVi = "Vỉ",
                            TenThuoc = "Metronidazole 250mg"
                        },
                        new
                        {
                            MaThuoc = "TH010",
                            DonVi = "Vỉ",
                            TenThuoc = "Dextromethorphan 15mg"
                        });
                });

            modelBuilder.Entity("QLBV.Models.ThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Thuoc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.ToaThuoc", b =>
                {
                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayKe")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MaToaThuoc")
                        .HasName("PK__ToaThuoc__6C278B89C44EA347");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaPk")
                        .IsUnique()
                        .HasFilter("[MaPk] IS NOT NULL");

                    b.ToTable("ToaThuoc");
                });

            modelBuilder.Entity("QLBV.Models.ToaThuocArchive", b =>
                {
                    b.Property<string>("ActionType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MaBacSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaToaThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayKe")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable("ToaThuoc_Archive");
                });

            modelBuilder.Entity("QLBV.Models.User_Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaNv")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MaNv")
                        .IsUnique()
                        .HasFilter("[MaNv] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QLBV.Models.User_Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaBsNavigation")
                        .WithOne("BacSi")
                        .HasForeignKey("QLBV.Models.BacSi", "MaBs")
                        .IsRequired()
                        .HasConstraintName("FK__BacSi__TrinhDo__412EB0B6");

                    b.Navigation("MaBsNavigation");
                });

            modelBuilder.Entity("QLBV.Models.CaTruc", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "NvtrucNavigation")
                        .WithMany("CaTrucs")
                        .HasForeignKey("Nvtruc")
                        .HasConstraintName("FK__CaTruc__NVtruc__440B1D61");

                    b.Navigation("NvtrucNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuKham", b =>
                {
                    b.HasOne("QLBV.Models.PhieuKhamBenh", "MaPkNavigation")
                        .WithMany()
                        .HasForeignKey("MaPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPhi__MaPK__534D60F1");

                    b.HasOne("QLBV.Models.ThuTuc", "MaTtNavigation")
                        .WithMany()
                        .HasForeignKey("MaTt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPhi__MaTT__5441852A");

                    b.Navigation("MaPkNavigation");

                    b.Navigation("MaTtNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLBV.Models.PhieuNhapThuoc", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaPhi__6754599E");

                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaThu__68487DD7");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ChiTietToaThuoc", b =>
                {
                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTo__MaThu__628FA481");

                    b.HasOne("QLBV.Models.ToaThuoc", "MaToaThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaToaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTo__MaToa__619B8048");

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("MaToaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.GiaBanThuoc", b =>
                {
                    b.HasOne("QLBV.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("GiaBanThuocs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__GiaBanThu__MaThu__6B24EA82");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QLBV.Models.Luong", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaNvNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__Luong__MaNV__5812160E");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.HasOne("QLBV.Models.PhongBan", "MaPbNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPb")
                        .HasConstraintName("FK__NhanVien__MaPB__3E52440B");

                    b.Navigation("MaPbNavigation");
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.HasOne("QLBV.Models.BacSi", "BacsiNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("Bacsi")
                        .HasConstraintName("FK__PhieuKham__Bacsi__4AB81AF0");

                    b.HasOne("QLBV.Models.SoKhamBenh", "MaSoKhamNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("MaSoKham");

                    b.HasOne("QLBV.Models.BenhNhan", "NguoiKhamNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("NguoiKham")
                        .HasConstraintName("FK__PhieuKham__Nguoi__4BAC3F29");

                    b.Navigation("BacsiNavigation");

                    b.Navigation("MaSoKhamNavigation");

                    b.Navigation("NguoiKhamNavigation");
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.HasOne("QLBV.Models.BoPhan", "MaBpNavigation")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaBp")
                        .HasConstraintName("FK__PhongBan__MoTa__3B75D760");

                    b.Navigation("MaBpNavigation");
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.HasOne("QLBV.Models.BenhNhan", "MaBnNavigation")
                        .WithMany("SoKhamBenhs")
                        .HasForeignKey("MaBn");

                    b.Navigation("MaBnNavigation");
                });

            modelBuilder.Entity("QLBV.Models.TaiKhoan", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "MaNvNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QLBV.Models.TaiKhoan", "MaNv")
                        .HasConstraintName("FK__TaiKhoan__MaNV__47DBAE45");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLBV.Models.ToaThuoc", b =>
                {
                    b.HasOne("QLBV.Models.BacSi", "MaBacSiNavigation")
                        .WithMany("ToaThuocs")
                        .HasForeignKey("MaBacSi")
                        .HasConstraintName("FK__ToaThuoc__MaBacS__5AEE82B9");

                    b.HasOne("QLBV.Models.PhieuKhamBenh", "MaPkNavigation")
                        .WithOne("ToaThuoc")
                        .HasForeignKey("QLBV.Models.ToaThuoc", "MaPk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MaBacSiNavigation");

                    b.Navigation("MaPkNavigation");
                });

            modelBuilder.Entity("QLBV.Models.User_Model.ApplicationUser", b =>
                {
                    b.HasOne("QLBV.Models.NhanVien", "NhanVien")
                        .WithOne("User")
                        .HasForeignKey("QLBV.Models.User_Model.ApplicationUser", "MaNv")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLBV.Models.BacSi", b =>
                {
                    b.Navigation("PhieuKhamBenhs");

                    b.Navigation("ToaThuocs");
                });

            modelBuilder.Entity("QLBV.Models.BenhNhan", b =>
                {
                    b.Navigation("PhieuKhamBenhs");

                    b.Navigation("SoKhamBenhs");
                });

            modelBuilder.Entity("QLBV.Models.BoPhan", b =>
                {
                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("QLBV.Models.NhanVien", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("CaTrucs");

                    b.Navigation("Luongs");

                    b.Navigation("TaiKhoan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLBV.Models.PhieuKhamBenh", b =>
                {
                    b.Navigation("ToaThuoc");
                });

            modelBuilder.Entity("QLBV.Models.PhieuNhapThuoc", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLBV.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLBV.Models.SoKhamBenh", b =>
                {
                    b.Navigation("PhieuKhamBenhs");
                });

            modelBuilder.Entity("QLBV.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("GiaBanThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
